data:
  class_path: data_loaders.whamr.WHAMRDataModule
  init_args:
    whamr_dir: /path/to/whamr/dir
    version: min
    target: anechoic
    sample_rate: 8000
    audio_time_len: [4.0, 4.0, null]
    batch_size: [2, 1]
